name: Fama
version: 1.0.0-beta.1.ha
slug: fama
description: Fama integrates Smart City systems from the German city of Solingen into smart home environments. Enabling seamless connectivity and functionality.
url: "https://github.com/nedeco/fama"
arch:
  - armv8
  - amd64
schema:
  enable_sensor_station: "bool"
  smart_home_type: "list(HA|IB)"
  mqtt_client_id: "str"
options:
  enable_sensor_station: true
  smart_home_type: HA
  mqtt_client_id: fama
init: false
boot: auto
services:
  - "mqtt:need"
image: "devopsnedeco/fama"
